// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	contracts "cowin/pkg/contracts"

	mock "github.com/stretchr/testify/mock"
)

// Notify is an autogenerated mock type for the Notify type
type Notify struct {
	mock.Mock
}

// Add provides a mock function with given fields: filter
func (_m *Notify) Add(filter contracts.Filter) error {
	ret := _m.Called(filter)

	var r0 error
	if rf, ok := ret.Get(0).(func(contracts.Filter) error); ok {
		r0 = rf(filter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Notify provides a mock function with given fields: centers, district
func (_m *Notify) Notify(centers []contracts.Center, district int) {
	_m.Called(centers, district)
}

// Remove provides a mock function with given fields: filterID, district
func (_m *Notify) Remove(filterID string, district int) error {
	ret := _m.Called(filterID, district)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = rf(filterID, district)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
